"""improve stage folw

Revision ID: 1d64d7a00aff
Revises: cdd2c70c748d
Create Date: 2026-02-23 15:03:26.107039

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '1d64d7a00aff'
down_revision: Union[str, Sequence[str], None] = 'cdd2c70c748d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('whatsapp_account', sa.Column('stage_flow', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('whatsapp_account', 'stage_prompt')
    op.add_column(
        "whatsapp_message", sa.Column("is_labeled", sa.Boolean(), nullable=True)
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('whatsapp_message', 'is_labeled')
    op.add_column('whatsapp_account', sa.Column('stage_prompt', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('whatsapp_account', 'stage_flow')
    # ### end Alembic commands ###
