"""add input output tokens in message table

Revision ID: 4eb873a31173
Revises: c1d2e3f4a5b6
Create Date: 2026-04-09 16:06:38.479640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4eb873a31173'
down_revision: Union[str, Sequence[str], None] = 'c1d2e3f4a5b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('whatsapp_message', sa.Column('input_tokens', sa.Integer(), nullable=True))
    op.add_column('whatsapp_message', sa.Column('output_tokens', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('whatsapp_message', 'output_tokens')
    op.drop_column('whatsapp_message', 'input_tokens')
    # ### end Alembic commands ###
