"""remove user_id to whatsapp_session

Revision ID: 58edd8b64223
Revises: 1d64d7a00aff
Create Date: 2026-02-26 14:49:38.261032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '58edd8b64223'
down_revision: Union[str, Sequence[str], None] = '1d64d7a00aff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('whatsapp_session_user_id_fkey'), 'whatsapp_session', type_='foreignkey')
    op.drop_column('whatsapp_session', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('whatsapp_session', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('whatsapp_session_user_id_fkey'), 'whatsapp_session', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
