"""add workspace_id to whatsapp_account

Revision ID: ae92f1cffd31
Revises: 03fead509a51
Create Date: 2026-03-31 17:16:08.121438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae92f1cffd31'
down_revision: Union[str, Sequence[str], None] = '03fead509a51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('whatsapp_account', sa.Column('workspace_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('whatsapp_account', 'workspace_id')
    # ### end Alembic commands ###
