"""add_stage_columns

Revision ID: cdd2c70c748d
Revises: bbeca83de7b1
Create Date: 2026-02-20 16:21:15.395882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cdd2c70c748d'
down_revision: Union[str, Sequence[str], None] = 'bbeca83de7b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('whatsapp_account', sa.Column('stage_prompt', sa.Text(), nullable=True))
    op.add_column('whatsapp_session', sa.Column('current_stage', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column('whatsapp_session', 'current_stage')
    op.drop_column('whatsapp_account', 'stage_prompt')
    # ### end Alembic commands ###
