"""add table for rag_file

Revision ID: f0f63f4c66f9
Revises: b2c3d4e5f6a7
Create Date: 2026-04-02 18:04:05.708407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0f63f4c66f9'
down_revision: Union[str, Sequence[str], None] = 'b2c3d4e5f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rag_documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('collection_name', sa.String(length=255), nullable=False),
    sa.Column('chunks_count', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rag_documents_collection_name'), 'rag_documents', ['collection_name'], unique=True)
    op.drop_index(op.f('ix_assistant_tool_account_id'), table_name='assistant_tool')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_assistant_tool_account_id'), 'assistant_tool', ['account_id'], unique=False)
    op.drop_index(op.f('ix_rag_documents_collection_name'), table_name='rag_documents')
    op.drop_table('rag_documents')
    # ### end Alembic commands ###
